### PR TITLE
fix: set-cookie header bug for tencent apigateway

### LINKED ISSUE #6: 返回多个cookie，只能获取到一个
```
app.post("/testCookie", (req, res, next) => {
  res.cookie("test0", '000');
  res.cookie("test1", 111);
  res.send('Cookie is set');
});
```
本地测试：
image

发布到serverless:
image

后台日志:
image

### PR DESCRIPTION
**Pull request by yugasun**
For tencent api gateway, it supports multi `Set-Cookie` in headers, so no need to transfer it. Otherwise only last cookie works.

Close #6

### CODE REVIEW

File: shims/index.js [hunk 1]
```diff
@@ -66,12 +66,8 @@ function forwardResponseToApiGateway(server, response, resolve) {
       // eslint-disable-next-line
       Object.keys(headers).forEach((h) => {
         if (Array.isArray(headers[h])) {
-          if (h.toLowerCase() === 'set-cookie') {
-            headers[h].forEach((value, i) => {
-              headers[binarycase(h, i + 1)] = value
-            })
-            delete headers[h]
-          } else {
+          // remove for for tecnent api gateway
```
Comment (pmuens) [inline shims/index.js]: Comment has a typo but IMHO let's not focus on that for this PR

**Review by pmuens — APPROVED** [review]

**Comment by yugasun** [comment]
@pmuens I use [tencent-serverless-nodejs](https://github.com/yugasun/tencent-serverless-nodejs) for http proxy, also add auto bundling handler file like [tencent-koa](https://github.com/serverless-components/tencent-koa) does. Could you help to review again?

**Review by pmuens — APPROVED** [review]

**Review by pmuens — APPROVED** [review]
